import { Response } from 'express';
import { AuthRequest } from '../middleware/auth.js';
import { NoticeService } from '../services/NoticeService.js';
import multer from 'multer';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import { existsSync, mkdirSync, renameSync, unlinkSync, readdirSync, statSync } from 'fs';
import { NoticeDataHelper } from '../data/NoticeDataHelper.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const noticeFlyersDir = join(__dirname, '../../data/Notice_Flyers');

// Configure multer for file uploads
const tempDir = join(noticeFlyersDir, '.temp');
if (!existsSync(tempDir)) {
  mkdirSync(tempDir, { recursive: true });
}

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, tempDir);
  },
  filename: (req, file, cb) => {
    const sanitized = file.originalname.replace(/[^a-zA-Z0-9.-]/g, '_');
    cb(null, `${Date.now()}-${sanitized}`);
  },
});

const upload = multer({
  storage: storage,
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB limit
  fileFilter: (req, file, cb) => {
    const allowedTypes = /jpeg|jpg|png|gif|webp/;
    const extname = allowedTypes.test(file.originalname.toLowerCase());
    const mimetype = allowedTypes.test(file.mimetype);
    if (extname && mimetype) {
      cb(null, true);
    } else {
      cb(new Error('Only image files are allowed (jpeg, jpg, png, gif, webp)'));
    }
  },
});

export class NoticeController {
  private noticeService: NoticeService;

  constructor() {
    this.noticeService = new NoticeService();
  }

  async getPublishedNotices(req: AuthRequest, res: Response): Promise<void> {
    try {
      const notices = await this.noticeService.getPublishedNotices();
      res.json(notices);
    } catch (error) {
      res.status(500).json({ error: 'Failed to fetch notices' });
    }
  }

  async getAllNotices(req: AuthRequest, res: Response): Promise<void> {
    try {
      const notices = await this.noticeService.getAllNotices();
      res.json(notices);
    } catch (error) {
      res.status(500).json({ error: 'Failed to fetch notices' });
    }
  }

  async getNoticeById(req: AuthRequest, res: Response): Promise<void> {
    try {
      const { id } = req.params;
      const notice = await this.noticeService.getNoticeById(id);
      if (!notice) {
        res.status(404).json({ error: 'Notice not found' });
        return;
      }
      res.json(notice);
    } catch (error) {
      res.status(500).json({ error: 'Failed to fetch notice' });
    }
  }

  async createNotice(req: AuthRequest, res: Response): Promise<void> {
    try {
      if (!req.user) {
        res.status(401).json({ error: 'Not authenticated' });
        return;
      }

      const { notice_name, notice_body, event_id, is_active, is_published } = req.body;

      if (!notice_name || !notice_body) {
        res.status(400).json({ error: 'Missing required fields: notice_name and notice_body are required' });
        return;
      }

      // notice_image_path will be auto-generated by the service when folder is created
      const notice = await this.noticeService.createNotice({
        notice_name,
        notice_body,
        event_id,
        is_active: is_active !== undefined ? is_active : true,
        is_published: is_published !== undefined ? is_published : false,
      });

      res.status(201).json(notice);
    } catch (error) {
      res.status(500).json({ error: 'Failed to create notice' });
    }
  }

  async updateNotice(req: AuthRequest, res: Response): Promise<void> {
    try {
      const { id } = req.params;
      const updates = req.body;

      const notice = await this.noticeService.updateNotice(id, updates);
      if (!notice) {
        res.status(404).json({ error: 'Notice not found' });
        return;
      }

      res.json(notice);
    } catch (error) {
      res.status(500).json({ error: 'Failed to update notice' });
    }
  }

  async deleteNotice(req: AuthRequest, res: Response): Promise<void> {
    try {
      const { id } = req.params;
      const success = await this.noticeService.deleteNotice(id);
      if (!success) {
        res.status(404).json({ error: 'Notice not found' });
        return;
      }

      res.json({ message: 'Notice deleted successfully' });
    } catch (error) {
      res.status(500).json({ error: 'Failed to delete notice' });
    }
  }

  async publishNotice(req: AuthRequest, res: Response): Promise<void> {
    try {
      const { id } = req.params;
      const notice = await this.noticeService.publishNotice(id);
      if (!notice) {
        res.status(404).json({ error: 'Notice not found' });
        return;
      }
      res.json(notice);
    } catch (error: any) {
      if (error.message && error.message.includes('Cannot publish an inactive notice')) {
        res.status(400).json({ error: error.message });
        return;
      }
      res.status(500).json({ error: 'Failed to publish notice' });
    }
  }

  async unpublishNotice(req: AuthRequest, res: Response): Promise<void> {
    try {
      const { id } = req.params;
      const notice = await this.noticeService.unpublishNotice(id);
      if (!notice) {
        res.status(404).json({ error: 'Notice not found' });
        return;
      }
      res.json(notice);
    } catch (error) {
      res.status(500).json({ error: 'Failed to unpublish notice' });
    }
  }

  // Upload images for notice (up to 3 files)
  uploadImages() {
    return upload.array('images', 3); // Up to 3 files
  }

  async handleImageUpload(req: AuthRequest, res: Response): Promise<void> {
    try {
      const noticeId = req.params.noticeId || req.params.id;
      
      const files = req.files as Express.Multer.File[];
      
      if (!files || files.length === 0) {
        res.status(400).json({ error: 'No files uploaded' });
        return;
      }

      if (files.length > 3) {
        // Clean up all uploaded files
        files.forEach(file => {
          if (existsSync(file.path)) {
            try {
              unlinkSync(file.path);
            } catch (cleanupError) {
              console.error('Error cleaning up temp file:', cleanupError);
            }
          }
        });
        res.status(400).json({ error: 'Maximum 3 images allowed' });
        return;
      }

      const notice = await this.noticeService.getNoticeById(noticeId);
      if (!notice) {
        // Delete temp files if notice not found
        files.forEach(file => {
          if (existsSync(file.path)) {
            try {
              unlinkSync(file.path);
            } catch (cleanupError) {
              console.error('Error cleaning up temp file:', cleanupError);
            }
          }
        });
        res.status(404).json({ error: 'Notice not found' });
        return;
      }

      // Get the notice folder name from notice_image_path
      const noticeDataHelper = new NoticeDataHelper();
      const folderName = notice.notice_image_path || `${notice.notice_name.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-').toLowerCase()}-${notice.notice_id}`;
      const targetFolder = join(noticeFlyersDir, folderName);

      // Ensure folder exists
      if (!existsSync(targetFolder)) {
        mkdirSync(targetFolder, { recursive: true });
      }

      // Move all files from temp to notice folder
      const uploadedFiles: Array<{ filename: string; imagePath: string }> = [];
      const errors: string[] = [];

      for (const file of files) {
        try {
          const targetPath = join(targetFolder, file.filename);
          renameSync(file.path, targetPath);
          uploadedFiles.push({
            filename: file.filename,
            imagePath: `${folderName}/${file.filename}`
          });
        } catch (error: any) {
          errors.push(`Failed to move ${file.originalname}: ${error.message}`);
          // Clean up temp file on error
          if (existsSync(file.path)) {
            try {
              unlinkSync(file.path);
            } catch (cleanupError) {
              console.error('Error cleaning up temp file:', cleanupError);
            }
          }
        }
      }

      // Update notice with image path (ensure it's set)
      if (uploadedFiles.length > 0 && !notice.notice_image_path) {
        await this.noticeService.updateNotice(noticeId, { notice_image_path: folderName });
      }

      if (errors.length > 0) {
        res.status(207).json({ 
          message: 'Some files uploaded with errors',
          uploaded: uploadedFiles,
          errors: errors
        });
      } else {
        res.json({ 
          message: `${uploadedFiles.length} image(s) uploaded successfully`,
          uploaded: uploadedFiles
        });
      }
    } catch (error: any) {
      console.error('Error uploading notice images:', error);
      // Clean up temp files on error
      if (req.files && Array.isArray(req.files)) {
        (req.files as Express.Multer.File[]).forEach(file => {
          if (existsSync(file.path)) {
            try {
              unlinkSync(file.path);
            } catch (cleanupError) {
              console.error('Error cleaning up temp file:', cleanupError);
            }
          }
        });
      }
      res.status(500).json({ error: 'Failed to upload images', details: error.message });
    }
  }

  // Get image file (public)
  async getNoticeImage(req: AuthRequest, res: Response): Promise<void> {
    try {
      const noticeId = req.params.noticeId || req.params.id;
      const { filename } = req.params;
      const notice = await this.noticeService.getNoticeById(noticeId);
      
      if (!notice || !notice.notice_image_path) {
        res.status(404).json({ error: 'Notice or image not found' });
        return;
      }

      const imagePath = join(noticeFlyersDir, notice.notice_image_path, filename);
      
      if (!existsSync(imagePath)) {
        res.status(404).json({ error: 'Image file not found' });
        return;
      }

      // Set appropriate Content-Type based on file extension
      const ext = filename.split('.').pop()?.toLowerCase();
      const contentTypeMap: Record<string, string> = {
        'jpg': 'image/jpeg',
        'jpeg': 'image/jpeg',
        'png': 'image/png',
        'gif': 'image/gif',
        'webp': 'image/webp',
      };
      const contentType = contentTypeMap[ext || ''] || 'image/jpeg';
      res.setHeader('Content-Type', contentType);
      
      // sendFile requires an absolute path
      const absolutePath = resolve(imagePath);
      res.sendFile(absolutePath);
    } catch (error) {
      res.status(500).json({ error: 'Failed to retrieve image' });
    }
  }

  // Delete image file
  async deleteNoticeImage(req: AuthRequest, res: Response): Promise<void> {
    try {
      const noticeId = req.params.noticeId || req.params.id;
      const { filename } = req.params;
      const notice = await this.noticeService.getNoticeById(noticeId);
      
      if (!notice || !notice.notice_image_path) {
        res.status(404).json({ error: 'Notice or image not found' });
        return;
      }

      const imagePath = join(noticeFlyersDir, notice.notice_image_path, filename);
      
      if (existsSync(imagePath)) {
        unlinkSync(imagePath);
      }

      res.json({ message: 'Image deleted successfully' });
    } catch (error) {
      res.status(500).json({ error: 'Failed to delete image' });
    }
  }

  // Get list of images for a notice (public)
  async getNoticeImages(req: AuthRequest, res: Response): Promise<void> {
    try {
      const noticeId = req.params.noticeId || req.params.id;
      console.log(`Getting images for notice: ${noticeId}`);
      
      const notice = await this.noticeService.getNoticeById(noticeId);
      
      if (!notice) {
        console.log(`Notice not found: ${noticeId}`);
        res.json([]);
        return;
      }

      if (!notice.notice_image_path) {
        console.log(`Notice ${noticeId} has no notice_image_path`);
        res.json([]);
        return;
      }

      const folderPath = join(noticeFlyersDir, notice.notice_image_path);
      console.log(`Looking for images in folder: ${folderPath}`);
      
      if (!existsSync(folderPath)) {
        console.log(`Folder does not exist: ${folderPath}`);
        res.json([]);
        return;
      }

      // Read all files in the folder
      const files = readdirSync(folderPath);
      console.log(`Found ${files.length} files in folder:`, files);
      
      const imageFiles = files
        .filter(file => {
          const filePath = join(folderPath, file);
          try {
            const stats = statSync(filePath);
            // Only include regular files (not directories) and image files
            const isImage = /\.(jpg|jpeg|png|gif|webp)$/i.test(file);
            const result = stats.isFile() && isImage;
            if (result) {
              console.log(`Including image file: ${file}`);
            }
            return result;
          } catch (error) {
            console.error(`Error checking file ${file}:`, error);
            return false;
          }
        })
        .map(filename => {
          const url = `/api/notices/${noticeId}/images/${encodeURIComponent(filename)}`;
          console.log(`Image URL for ${filename}: ${url}`);
          return {
            filename,
            url,
          };
        })
        .sort((a, b) => a.filename.localeCompare(b.filename));

      console.log(`Returning ${imageFiles.length} images for notice ${noticeId}`);
      res.json(imageFiles);
    } catch (error: any) {
      console.error(`Error getting images for notice ${req.params.noticeId || req.params.id}:`, error);
      res.json([]); // Return empty array instead of error
    }
  }
}

